version: '3'
services:
  proxy:
    image: nginx:latest
    container_name: 'proxy'
    volumes:
      - ./nginx/conf:/etc/nginx/
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - 'web'
    restart: always
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - $GOPATH/src:/go/src
      - ./mysql/log:/var/log/mysql
      - ./nginx/log:/var/log/nginx
    working_dir: "/go/src/github.com/gosagawa/isucon"
    command: bash -c "/go/wait-for-it/wait-for-it.sh db:3306 -- goose up; realize start --name='isucon' --run"
    depends_on:
      - 'db'
    tty: true
    privileged: true
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: isucon
